ALTER TABLE "SYS_OSS_CONFIG" ADD ("ACCESS_POLICY" CHAR(1) DEFAULT '1' NOT NULL);

COMMENT ON COLUMN "SYS_OSS_CONFIG"."ACCESS_POLICY" IS '桶权限类型(0=private 1=public 2=custom)';

ALTER TABLE "WF_DEPLOY_FORM" ADD ("FORM_NAME" VARCHAR(64) default '');

COMMENT ON COLUMN "WF_DEPLOY_FORM"."FORM_NAME" IS '表单名称';
